-- MySQL Script generated by MySQL Workbench
-- Fri May 27 00:23:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pec_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pec_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pec_database` DEFAULT CHARACTER SET utf8 ;
USE `pec_database` ;

-- -----------------------------------------------------
-- Table `pec_database`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Students` (
  `studentID` INT UNSIGNED NOT NULL,
  `username` VARCHAR(16) NULL DEFAULT NULL,
  `firstName` VARCHAR(30) NULL DEFAULT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `school` ENUM('UET', 'ULIS', 'IS', 'UEd', 'UEB', 'SoL') NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `modifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Weekdays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Weekdays` (
  `weekdayNumber` TINYINT(1) UNSIGNED NOT NULL,
  `dayOfWeek` ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
  PRIMARY KEY (`weekdayNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Subjects` (
  `subjectCode` VARCHAR(8) NOT NULL,
  `subjectName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`subjectCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Classes` (
  `classCode` VARCHAR(11) GENERATED ALWAYS AS (CONCAT(`subjectCode`, " ", `classNumber`)) VIRTUAL,
  `subjectCode` VARCHAR(8) NOT NULL,
  `classNumber` TINYINT(2) NOT NULL,
  `weekdayNumber` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `startTime` TIME NOT NULL,
  `studyTime` TIME NOT NULL,
  `numberOfStudents` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`subjectCode`, `classNumber`),
  INDEX `weekdayNumber_fk_idx` (`weekdayNumber` ASC) VISIBLE,
  INDEX `subjectCode_fk_idx` (`subjectCode` ASC) VISIBLE,
  INDEX `weekdayNumber_fk` (`weekdayNumber` ASC) VISIBLE,
  CONSTRAINT `weekdayNumber_fk`
    FOREIGN KEY (`weekdayNumber`)
    REFERENCES `pec_database`.`Weekdays` (`weekdayNumber`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `subjectCode_fk`
    FOREIGN KEY (`subjectCode`)
    REFERENCES `pec_database`.`Subjects` (`subjectCode`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`AttendingStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`AttendingStudents` (
  `studentID` INT UNSIGNED NOT NULL,
  `classCode` VARCHAR(11) GENERATED ALWAYS AS (CONCAT(subjectCode, " ", classNumber)) VIRTUAL,
  `subjectCode` VARCHAR(8) NULL DEFAULT NULL,
  `classNumber` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`studentID`),
  INDEX `classCode_Students_fk` (`subjectCode` ASC, `classNumber` ASC) VISIBLE,
  INDEX `classCode_AttendingStudents_fk` (`subjectCode` ASC, `classNumber` ASC) VISIBLE,
  CONSTRAINT `classCode_AttendingStudents_fk`
    FOREIGN KEY (`subjectCode` , `classNumber`)
    REFERENCES `pec_database`.`Classes` (`subjectCode` , `classNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `pec_database`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Admins` (
  `adminID` INT UNSIGNED NOT NULL,
  `username` VARCHAR(16) NULL DEFAULT NULL,
  `firstName` VARCHAR(30) NULL DEFAULT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `modifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Products` (
  `itemCode` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NOT NULL,
  `availableQuantity` INT UNSIGNED NOT NULL,
  `category` ENUM('SPORT_EQUIPMENT', 'UNIFORM') NOT NULL DEFAULT 'SPORT_EQUIPMENT',
  `primaryImage` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT(100) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `modifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`itemCode`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `pec_database`.`Carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Carts` (
  `userID` INT UNSIGNED NOT NULL,
  `itemCode` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT UNSIGNED NOT NULL,
  `type` VARCHAR(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`userID`, `itemCode`, `type`),
  INDEX `itemCode_Carts_fk_idx` (`itemCode` ASC) VISIBLE,
  INDEX `itemCode_Carts_fk` (`itemCode` ASC) VISIBLE,
  CONSTRAINT `userID_Carts_fk`
    FOREIGN KEY (`userID`)
    REFERENCES `pec_database`.`Students` (`studentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `itemCode_Carts_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Products` (`itemCode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`SportEquipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`SportEquipments` (
  `itemCode` INT UNSIGNED NOT NULL,
  `category` ENUM('BALL', 'NET', 'PROTECTION') NULL DEFAULT NULL,
  PRIMARY KEY (`itemCode`),
  CONSTRAINT `itemCode_SportEquipments_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Products` (`itemCode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Requests` (
  `requestNumber` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `studentID` INT UNSIGNED NOT NULL,
  `requestDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NULL DEFAULT NULL,
  `classCode` VARCHAR(11) NULL DEFAULT NULL,
  `statusID` TINYINT(2) NOT NULL DEFAULT 1,
  `note` TEXT(50) NULL DEFAULT NULL,
  `modifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`requestNumber`),
  INDEX `studentID_Requests_fk_idx` (`studentID` ASC) VISIBLE,
  INDEX `studentID_Requests_fk` (`studentID` ASC) VISIBLE,
  CONSTRAINT `studentID_Requests_fk`
    FOREIGN KEY (`studentID`)
    REFERENCES `pec_database`.`Students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`RequestDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`RequestDetails` (
  `requestNumber` INT UNSIGNED NOT NULL,
  `itemCode` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`requestNumber`, `itemCode`),
  INDEX `itemCode_RequestDetails_fk_idx` (`itemCode` ASC) VISIBLE,
  INDEX `itemCode_RequestDetails_fk` (`itemCode` ASC) VISIBLE,
  CONSTRAINT `requestNumber_RequestDetails_fk`
    FOREIGN KEY (`requestNumber`)
    REFERENCES `pec_database`.`Requests` (`requestNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `itemCode_RequestDetails_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`SportEquipments` (`itemCode`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Orders` (
  `orderNumber` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `studentID` INT UNSIGNED NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `receivedDate` DATETIME NULL DEFAULT NULL,
  `statusID` TINYINT(2) NOT NULL DEFAULT 1,
  `note` TEXT(100) NULL DEFAULT NULL,
  `modifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
  `paymentMethod` ENUM('BANKING', 'DIRECT') NOT NULL DEFAULT 'DIRECT',
  PRIMARY KEY (`orderNumber`),
  INDEX `studentID_Orders_fk_idx` (`studentID` ASC) VISIBLE,
  INDEX `studentID_Orders_fk` (`studentID` ASC) VISIBLE,
  CONSTRAINT `studentID_Orders_fk`
    FOREIGN KEY (`studentID`)
    REFERENCES `pec_database`.`Students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Uniforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Uniforms` (
  `itemCode` INT UNSIGNED NOT NULL,
  `priceEach` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`itemCode`),
  CONSTRAINT `itemCode_Uniforms_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Products` (`itemCode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`orderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`orderDetails` (
  `orderNumber` INT UNSIGNED NOT NULL,
  `itemCode` INT UNSIGNED NOT NULL,
  `size` VARCHAR(5) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderNumber`, `itemCode`, `size`),
  INDEX `itemCode_OrderDetails_fk_idx` (`itemCode` ASC) VISIBLE,
  INDEX `itemCode_OrderDetails_fk` (`itemCode` ASC) VISIBLE,
  CONSTRAINT `orderNumber_OrderDetails_fk`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `pec_database`.`Orders` (`orderNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `itemCode_OrderDetails_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Uniforms` (`itemCode`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`UniformSizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`UniformSizes` (
  `itemCode` INT UNSIGNED NOT NULL,
  `size` VARCHAR(5) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`itemCode`, `size`),
  CONSTRAINT `itemCode_UniformSizes_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Uniforms` (`itemCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`ProductImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`ProductImages` (
  `itemCode` INT UNSIGNED NOT NULL,
  `uri` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`itemCode`, `uri`),
  CONSTRAINT `itemCode_ProductImages_fk`
    FOREIGN KEY (`itemCode`)
    REFERENCES `pec_database`.`Products` (`itemCode`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`RequestStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`RequestStatus` (
  `statusID` TINYINT(2) UNSIGNED NOT NULL,
  `statusName` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`statusName` ASC) VISIBLE,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`OrderStatus` (
  `statusID` TINYINT(2) UNSIGNED NOT NULL,
  `statusName` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`statusName` ASC) VISIBLE,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pec_database`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pec_database`.`Payments` (
  `PaymentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `studentID` INT UNSIGNED NOT NULL,
  `orderNumber` INT UNSIGNED NOT NULL,
  `paymentDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`PaymentID`),
  INDEX `userID_Payments_fk_idx` (`studentID` ASC) VISIBLE,
  INDEX `orderNumber_Payments_fk_idx` (`orderNumber` ASC) VISIBLE,
  INDEX `studentID_Payments_fk` (`studentID` ASC) VISIBLE,
  INDEX `orderNumber_Payments_fk` (`orderNumber` ASC) VISIBLE,
  CONSTRAINT `studentID_Payments_fk`
    FOREIGN KEY (`studentID`)
    REFERENCES `pec_database`.`Students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `orderNumber_Payments_fk`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `pec_database`.`Orders` (`orderNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
